[package]
name = "circuit"
type = "bin"
authors = []
# Update compiler version to match dependency requirement
compiler_version = ">=1.0.0"

[dependencies]
# Point to the local, vendored library - REMOVED
base64 = { tag = "v0.4.0", git = "https://github.com/noir-lang/noir_base64" }
bignum = { tag = "v0.6.1", git = "https://github.com/noir-lang/noir-bignum" }
rsa = { tag = "main", git = "https://github.com/zkpassport/noir_rsa" }
sha256 = { tag = "v0.1.3", git = "https://github.com/noir-lang/sha256" }



